name: pokedex_clean_arch
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.6.0
  get_it: ^7.7.0
  injectable: ^2.4.4
  build_runner: ^2.4.12
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true