// Mocks generated by Mockito 5.4.4 from annotations
// in pokedex_clean_arch/test/modules/home/data/repositories/pokemon_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pokedex_clean_arch/modules/home/data/datasources/pokemon_datasource.dart'
    as _i3;
import 'package:pokedex_clean_arch/modules/home/domain/entities/pokemon_base_entity.dart'
    as _i5;
import 'package:pokedex_clean_arch/modules/home/domain/entities/pokemon_entity.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonEntity_0 extends _i1.SmartFake implements _i2.PokemonEntity {
  _FakePokemonEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokemonDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonDatasource extends _i1.Mock implements _i3.PokemonDatasource {
  MockPokemonDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.PokemonBaseEntity>> fetchPokemonBaseList(
          int? pageNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPokemonBaseList,
          [pageNumber],
        ),
        returnValue: _i4.Future<List<_i5.PokemonBaseEntity>>.value(
            <_i5.PokemonBaseEntity>[]),
      ) as _i4.Future<List<_i5.PokemonBaseEntity>>);

  @override
  _i4.Future<_i2.PokemonEntity> fetchPokemon(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPokemon,
          [name],
        ),
        returnValue: _i4.Future<_i2.PokemonEntity>.value(_FakePokemonEntity_0(
          this,
          Invocation.method(
            #fetchPokemon,
            [name],
          ),
        )),
      ) as _i4.Future<_i2.PokemonEntity>);
}
